<?php

/**
 * Implements hook_menu().
 */
function nuenenen_api_menu() { 
  $items['node/%node/json'] = array(
    'page callback' => 'nuenenen_api_endpoint',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
  );

  $items[drupal_get_path_alias().'/json'] = array(
    'page callback' => 'nuenenen_api_endpoint',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
  );

  return $items;
}

/**
 * Menu callback for the node JSON endpoint.
 *
 * @param $node
 *   A node object.
 * 
 * @return
 *   Returns node as JSON.
 */
function nuenenen_api_endpoint($node) {
  drupal_json_output($node);
}
